services:
  web:
    build: ./gerobug_web
    command: gunicorn gerobug_web.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    depends_on:
      - dashboard
    networks:
      - default
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.gerobug-web.rule: "Host(`gerobug.${DOMAIN_NAME}`)"
      traefik.http.routers.gerobug-web.entrypoints: "https"
      traefik.http.routers.gerobug-web.tls.certresolver: "letsencrypt"
      traefik.http.services.gerobug-web.loadbalancer.server.port: "8000"
    logging:
      options:
        max-size: 50m

  dashboard:
    build: ./gerobug_dashboard
    command: gunicorn gerobug.wsgi --bind 0.0.0.0:8001 --timeout 300
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      GEROBUG_HOST: "gerobug.${DOMAIN_NAME},gerobug-dashboard.${DOMAIN_NAME}"
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.gerobug-dashboard.rule: "Host(`gerobug-dashboard.${DOMAIN_NAME}`)"
      traefik.http.routers.gerobug-dashboard.entrypoints: "https"
      traefik.http.routers.gerobug-dashboard.tls.certresolver: "letsencrypt"
      traefik.http.services.gerobug-dashboard.loadbalancer.server.port: "8001"
    logging:
      options:
        max-size: 50m

  db:
    image: "postgres:17-alpine"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "gerobug_db"
      POSTGRES_USER: "gerobug"
    volumes:
      - ${APPS_FOLDER}/gerobug/db_data/:/var/lib/postgresql/data/
    restart: unless-stopped
    logging:
      options:
        max-size: 50m

networks:
  traefik:
    external: true
